import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BookingProvider } from "./context/BookingContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Salon Booking Online",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-white w-full h-svh rounded-lg shadow-xl p-5 text-black">
          <BookingProvider>
            {children}
          </BookingProvider>
        </div>

        <footer className="absolute bottom-0 bg-white text-black w-full rounded-lg text-center p-2 font-medium text-sm">Copyright &copy; 2025 <span className="text-yellow-600">Salon Booking Online</span></footer>
      </body>
    </html>
  );
}
